version: '3.7'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PROJECT_DIR}:/var/www/apps/:rw
      - ./nginx/conf.d/:/etc/nginx/conf.d/:rw
      - ./nginx/certs/:/etc/nginx/ssl/:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./nginx/mime.types:/etc/nginx/conf/mime.types:ro
      - ./nginx/fastcgi_params:/etc/nginx/fastcgi_params:ro
      - ./nginx/log/:/var/log/nginx/:rw
      - ./nginx/entrypoint.sh:/usr/share/nginx/entrypoint.sh:rw
    environment:
      TZ: "${TZ}"
    entrypoint: /usr/share/nginx/entrypoint.sh
    links:
      - "php"
    container_name: nginx

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf:rw
      - ./mysql/data/:/var/lib/mysql/:rw
    security_opt:
      - seccomp:unconfined
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: "${TZ}"
      MYSQL_ROOT_PASSWORD: OK!strEver
      MYSQL_DATABASE: db_demo
      MYSQL_USER: db_user_demo
      MYSQL_PASSWORD: passWord@db_demo
    container_name: mysql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis.conf:ro
      - ./redis/data:/usr/local/redis/data
    container_name: redis
    env_file:
      - .env

  php:
    build:
      context: ./php
    volumes:
      - ${PROJECT_DIR}:/var/www/apps/:rw
      - ./php/php.ini-development:/usr/local/etc/php/php.ini:rw
      - ./php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
    environment:
      TZ: "${TZ}"
      PHP_EXT_REDIS_VERSION : "${PHP_EXT_REDIS_VERSION}"
    expose:
      - "9000"
    links:
      - "mysql"
      - "redis"
    container_name: php

